### ISSUE TITLE
Layout Inheritance not working like documented?

### ISSUE THREAD

**Issue by Nadaron** [thymeleaf/thymeleaf#1010]
I'm trying to use Thymeleaf 3.1.2 to render some nasty email templates, which involve lots of direct styles and formatting. So basically I have a general layout for all emails and want to add a specific content block in the middle. Reading the tutorial, I think "Layout Inheritance" (https://www.thymeleaf.org/doc/tutorials/3.1/usingthymeleaf.html#layout-inheritance) is what I need to use to achieve the best result.

After struggling with my own templates, I copied the examples out of the docs and they also didn't work, so I'm wondering. 

I created a "layoutFile.html" and copied the example code to it:
```
<!DOCTYPE html>
<html th:fragment="layout (title, content)" xmlns:th="http://www.thymeleaf.org">
<head>
    <title th:replace="${title}">Layout Title</title>
</head>
<body>
    <h1>Layout H1</h1>
    <div th:replace="${content}">
        <p>Layout content</p>
    </div>
    <footer>
        Layout footer
    </footer>
</body>
</html>
```
Then the template itself "test.html":
```
<!DOCTYPE html>
<html th:replace="~{layoutFile :: layout(~{::title}, ~{::section})}">
<head>
    <title>Page Title</title>
</head>
<body>
<section>
    <p>Page content</p>
    <div>Included on page</div>
</section>
</body>
</html>
```

If I then try to process the "test" template, I get an exception:
```
org.thymeleaf.exceptions.TemplateInputException: Error resolving fragment: "${title}": template or fragment could not be resolved (template: "layoutFile" - line 4, col 12)
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor.doProcess(AbstractStandardFragmentInsertionTagProcessor.java:123) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.engine.Model.process(Model.java:282) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1064) ~[thymeleaf-3.1.2.RELEASE.jar:?]
	at thymeleaf@3.1.2.RELEASE/org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1053) ~[thymeleaf-3.1.2.RELEASE.jar:?]
[...]
```

This is the same exception I get with my own templates. Do I miss something here?
I would instead expect the following output:
```
<!DOCTYPE html>
<html>
<head>
    <title>Page Title</title>
</head>
<body>
    <h1>Layout H1</h1>
    <section>
        <p>Page content</p>
        <div>Included on page</div>
    </section>
    <footer>
        Layout footer
    </footer>
</body>
</html>
```

**Comment by AdrianHamod** [comment]
I noticed the same issue. It's very confusing.

**Comment by danielfernandez** [comment]
This error indicates that your `test.html` is not finding the fragment you are specifying for the `title` argument of the fragment. Said otherwise, your `~{::title}` does not match any fragment.

This said, if your code is exactly this:
```html
<!DOCTYPE html>
<html th:replace="~{layoutFile :: layout(~{::title}, ~{::section})}">
<head>
    <title>Page Title</title>
</head>
<body>
<section>
    <p>Page content</p>
    <div>Included on page</div>
</section>
</body>
</html>
```
Then `~{::title}` should be resolving to:

```html
<title>Page Title</title>
```
And this has been tested to be working OK with Thymeleaf 3.1.2 or 3.1.3. So it if not in your case, I'm guessing perhaps your code is not exactly this, or there is some copy-pasting issue, perhaps a wrong tag name or similar.

I'm closing this for now as it is not reproducible. Please feel free to reopen if there is further information you can provide showing the specifics of the error you are getting (e.g. exactly how you initialize your `TemplateEngine` object).
