### ISSUE TITLE
Unexpected "Calling method 'containsBean' is forbidden" exception

### ISSUE THREAD

**Issue by candrews** [thymeleaf/thymeleaf#1025]
I have an application that is working with Spring Boot 3.4.0, but with 3.4.1, I get an unexpected exception:

`org.springframework.expression.EvaluationException: Calling method 'containsBean' is forbidden for type 'class org.springframework.web.context.support.GenericWebApplicationContext' in this expression context.`

The Thymeleaf excerpt is:
```
  <head th:with="elasticApmConfiguration=${T(org.thymeleaf.spring6.context.SpringContextUtils).getApplicationContext(#ctx).containsBean('someBean')?T(org.thymeleaf.spring6.context.SpringContextUtils).getApplicationContext(#ctx).getBean('someBean'):null}"
```

I don't see why calling the `containsBean` method invocation should be forbidden in this context.

Here's the full exception stack trace:
```
Caused by: org.springframework.expression.EvaluationException: Calling method 'containsBean' is forbidden for type 'class org.springframework.web.context.support.GenericWebApplicationContext' in this expression context.
	at app//org.thymeleaf.spring6.expression.ThymeleafEvaluationContext$ThymeleafEvaluationContextACLMethodResolver.resolve(ThymeleafEvaluationContext.java:276)
	at app//org.springframework.expression.spel.ast.MethodReference.findAccessorForMethod(MethodReference.java:218)
	at app//org.springframework.expression.spel.ast.MethodReference.getValueInternal(MethodReference.java:148)
	at app//org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:398)
	at app//org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:97)
	at app//org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:203)
	at app//org.springframework.expression.spel.ast.Ternary.getValueInternal(Ternary.java:54)
	at app//org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:116)
	at app//org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:338)
	at app//org.thymeleaf.spring6.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:265)
	... 254 more
```

I suspect that this issue originates with https://github.com/thymeleaf/thymeleaf/commit/2f1298367fd73caa0f5121803d682bfc3a77c3ce

I believe that getting beans as I'm doing here should be allowed - if not, is there some alternative approach that is allowed?

**Comment by agebhar1** [comment]
Hi @candrews, faced a similar issue while restricting method calls for `Class` #1027.

This issue for `org.springframework.web.context.support.GenericWebApplicationContext`  was introduced in a459a02fe21604f453c0426bad9203027d588687. `org.springframework.web.context.support.GenericWebApplicationContext` implements `org.springframework.core.io.ResourceLoader` and thus it's blocked/forbidden.

**Comment by candrews** [comment]
> Hi @candrews, faced a similar issue while restricting method calls for `Class` #1027.
> 
> This issue for `org.springframework.web.context.support.GenericWebApplicationContext` was introduced in [a459a02](https://github.com/thymeleaf/thymeleaf/commit/a459a02fe21604f453c0426bad9203027d588687). `org.springframework.web.context.support.GenericWebApplicationContext` implements `org.springframework.core.io.ResourceLoader` and thus it's blocked/forbidden.

Thank you for that information!

It seems that the check is too strict - perhaps the intent is to prevent calling any methods provided by `BLOCKED_MEMBER_CALL_JAVA_SUPERS_NAMES` classes/interfaces, and not prevent use of any object that implements any of those classes/interfaces?

There has to be some way to address this regression...

**Comment by danielfernandez** [comment]
This is intended as a part of the measures to further secure expression execution. Unfortunately, although I definitely sympathize with code that ceases to work because of this, security auditors keep requesting even tighter limits for what can and cannot be executed in Thymeleaf expressions and this tendency of restricting more classes with each version will only speed up.

This said, I would definitely recommend that code such as bean management be done in Java code at the controller (or other) layers, not the view-layer templates.
