### ISSUE TITLE
Literal URLs cause generic java.lang.NumberFormatException

### ISSUE THREAD

**Issue by ugate** [thymeleaf/thymeleaf#203]
In Thymeleaf 2.0.17 a generic java.lang.NumberFormatException is thrown when using a literal URL instead of the normal URL expression @{}

``` html
<script 
th:src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
```

I know that this is just improper usage, but I thought it may be somewhat obscure for a newbe to track down the cause:

``` java
Error during execution of processor 'org.thymeleaf.standard.processor.attr.StandardSingleNonRemovableAttributeModifierAttrProcessor' (example:462)] with root cause
java.lang.NumberFormatException
    at java.math.BigDecimal.<init>(BigDecimal.java:464)
    at java.math.BigDecimal.<init>(BigDecimal.java:739)
    at org.thymeleaf.standard.expression.NumberLiteralExpression.<init>(NumberLiteralExpression.java:55)
    at org.thymeleaf.standard.expression.NumberLiteralExpression.parseNumberLiteral(NumberLiteralExpression.java:73)
    at org.thymeleaf.standard.expression.SimpleExpression.decomposeSimpleExpressions(SimpleExpression.java:103)
    at org.thymeleaf.standard.expression.SimpleExpression.decomposeSimpleExpressions(SimpleExpression.java:63)
    at org.thymeleaf.standard.expression.Expression.parse(Expression.java:75)
    at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:184)
    at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:72)
    at org.thymeleaf.standard.expression.StandardExpressionProcessor.parseExpression(StandardExpressionProcessor.java:55)
    at org.thymeleaf.standard.expression.StandardExpressionProcessor.processExpression(StandardExpressionProcessor.java:164)
    at org.thymeleaf.standard.processor.attr.AbstractStandardSingleAttributeModifierAttrProcessor.getTargetAttributeValue(AbstractStandardSingleAttributeModifierAttrProcessor.java:59)
    at org.thymeleaf.processor.attr.AbstractSingleAttributeModifierAttrProcessor.getModifiedAttributeValues(AbstractSingleAttributeModifierAttrProcessor.java:59)
    at org.thymeleaf.processor.attr.AbstractAttributeModifierAttrProcessor.processAttribute(AbstractAttributeModifierAttrProcessor.java:61)
    at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:74)
    at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
    at org.thymeleaf.dom.Node.applyNextProcessor(Node.java:914)
    at org.thymeleaf.dom.Node.processNode(Node.java:869)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:638)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:620)
    at org.thymeleaf.dom.Node.processNode(Node.java:888)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:638)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:620)
    at org.thymeleaf.dom.Node.processNode(Node.java:888)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:638)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:620)
    at org.thymeleaf.dom.Node.processNode(Node.java:888)
    at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:638)
    at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:620)
    at org.thymeleaf.dom.Node.processNode(Node.java:888)
    at org.thymeleaf.dom.Document.process(Document.java:93)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1243)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1148)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1095)
```

**Comment by danielfernandez** [comment]
The reason you're receiving such exception is that everything in a th:src must be a Thymeleaf standard expression. And literals in standard expressions must be surrounded by single quotes.

Thymeleaf is trying to parse your url not considering it a literal, sees some symbols that look as a division and... the exception raises.

**Comment by ugate** [comment]
Yeah, I figured that out after further investigation. The reason for the issue is that the exception is somewhat cryptic and misleading :)

**Comment by SkipLOC** [comment]
I believe I'm getting the same issue when trying to link to .css files with a '-' in the name, for example jquery-ui-1.10.3.custom.min.css.
For example, this line: 
<code>
&lt; link href="../../css/jqueryui/1.10.3/themes/smoothness/jquery-ui-1.10.3.custom.min.css" th:href="@{/css/jqueryui/1.10.3/themes/smoothness/jquery-ui-1.10.3.custom.min.css}" rel="stylesheet" media="screen" / &gt;
</code>
Causes an error. I am still looking for a solution.

**Comment by danielfernandez** [comment]
@SkipLOC are you using 2.1.0-beta1? if so, your issue might be this: thymeleaf/thymeleaf#210

**Comment by SkipLOC** [comment]
Thanks for the speedy reply.
I'm using 2.1.0-m3
I had to remove the directory '1.10.3' and escape the '-' symbols with a '\'

**Comment by danielfernandez** [comment]
@SkipLOC OK. 2.1.0-beta2 will soon be out. In the meantime, you can use 2.1.0-SNAPSHOT, which is already updated with that fix. You can read more about using snapshots here: http://www.thymeleaf.org/faq.html
