### ISSUE TITLE
throw NumberFormatException in 'th:href' contains invalid number string, version 2.1.0-beta1

### ISSUE THREAD

**Issue by evanfeng** [thymeleaf/thymeleaf#210]
Example : 

```
<link href="http://netdna.bootstrapcdn.com/twitter-bootstrap/2.3.0/css/bootstrap.min.css"
    th:href="@{/webjars/bootstrap/2.3.0/css/bootstrap.min.css}" rel="stylesheet"/>
```

Error stack : 

Caused by: java.lang.NumberFormatException: null
    at java.math.BigDecimal.<init>(BigDecimal.java:453) ~[na:1.6.0_51]
    at java.math.BigDecimal.<init>(BigDecimal.java:728) ~[na:1.6.0_51]
    at org.thymeleaf.standard.expression.NumberTokenExpression.<init>(NumberTokenExpression.java:51) ~[classes/:na]
    at org.thymeleaf.standard.expression.NumberTokenExpression.parseNumberToken(NumberTokenExpression.java:74) ~[classes/:na]
    at org.thymeleaf.standard.expression.ExpressionParsingUtil.parseAsToken(ExpressionParsingUtil.java:375) ~[classes/:na]
    at org.thymeleaf.standard.expression.ExpressionParsingUtil.finishCurrentToken(ExpressionParsingUtil.java:351) ~[classes/:na]
    at org.thymeleaf.standard.expression.ExpressionParsingUtil.decomposeSimpleExpressions(ExpressionParsingUtil.java:132) ~[classes/:na]
    at org.thymeleaf.standard.expression.ExpressionParsingUtil.decompose(ExpressionParsingUtil.java:94) ~[classes/:na]
    at org.thymeleaf.standard.expression.Expression.parse(Expression.java:73) ~[classes/:na]
    at org.thymeleaf.standard.expression.LinkExpression.parseBaseDefaultAsLiteral(LinkExpression.java:215) ~[classes/:na]
    at org.thymeleaf.standard.expression.LinkExpression.parseLink(LinkExpression.java:196) ~[classes/:na]
    at org.thymeleaf.standard.expression.ExpressionParsingUtil.decomposeSimpleExpressions(ExpressionParsingUtil.java:236) ~[classes/:na]
    at org.thymeleaf.standard.expression.ExpressionParsingUtil.decompose(ExpressionParsingUtil.java:94) ~[classes/:na]
    at org.thymeleaf.standard.expression.Expression.parse(Expression.java:73) ~[classes/:na]
    at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:204) ~[classes/:na]
    at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:72) ~[classes/:na]
    at org.thymeleaf.standard.expression.StandardExpressionProcessor.parseExpression(StandardExpressionProcessor.java:55) ~[classes/:na]
    at org.thymeleaf.standard.expression.StandardExpressionProcessor.processExpression(StandardExpressionProcessor.java:180) ~[classes/:na]
    at org.thymeleaf.standard.processor.attr.AbstractStandardSingleAttributeModifierAttrProcessor.getTargetAttributeValue(AbstractStandardSingleAttributeModifierAttrProcessor.java:60) ~[classes/:na]

**Comment by danielfernandez** [comment]
This happened because the "2.3.0" was mistakenly parsed as if it were a number literal, and it failed because it contained two decimal point symbols.

Updated 2.1.0-SNAPSHOT with this fix.
