### ISSUE TITLE
org.xml.sax.SAXException: Scanner State 24 not Recognized

### ISSUE THREAD

**Issue by opensource21** [thymeleaf/thymeleaf#220]
Seems to be a regression: https://github.com/thymeleaf/thymeleaf/issues/37
It happens after changing encoding to UTF-8!
Tested with 2.0.17 and 2.0.18

**Comment by danielfernandez** [comment]
Would you be able to share the template file that raises this error when parsing? If it only happens when encoding is set to a specific value, my first thought is this could be an issue in the `TemplateProcessingReader`, but it might be very specific, so it would be nice if we could have the template causing this...

**Comment by opensource21** [comment]
Yes I send it via Mail to you. I figured out that with 2.0.8 I get another error:

```
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content ist nicht zulässig in Prolog.
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:198)
    at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:441)
    at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:368)
    at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1388)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl$PrologDriver.next(XMLDocumentScannerImpl.java:998)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:607)
    at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:489)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:835)
    at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:764)
    at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:123)
    at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1210)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:568)
    at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:302)
    at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.doParse(AbstractNonValidatingSAXTemplateParser.java:183)
    at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplateUsingPool(AbstractNonValidatingSAXTemplateParser.java:115)
```

**Comment by opensource21** [comment]
Added Xerces as a dependency and get them with Thymeleaf 2.0.17 an error with leads me to
http://stackoverflow.com/questions/5138696/org-xml-sax-saxparseexception-content-is-not-allowed-in-prolog. If I convert the files to UTF-8 without BOM everything works fine. Even if I drop xerces from classpath.

**Comment by danielfernandez** [comment]
Thanks for your files. I've just been able to fix this.

Given thymeleaf parsers work at a `char[]` level, there is no need to preserve the Byte Order Mark symbols, so I've modified the template parser reader to just skip them and not cause any problems during parsing.

Both the _Scanner State 24 not Recognized_ (xerces not in classpath) and the _Content is not allowed in prolog_ (xerces in classpath) errors should now be gone.

**Comment by danielfernandez** [comment]
Updated 2.0.19-SNAPSHOT and 2.1.0-SNAPSHOT.

**Comment by opensource21** [comment]
Two further information:
1. On Unix and with Eclipse the files are normally UTFwithoutBOM so the problem only happens if someone use a converter. So it's not a blocker, sorry for describing it so dramatic.
2.  As far as I understand the BOM is only the first byte, so there is no need to check it everywhere. As I understand a check everywhere could have side effects.  Following the German Wikipedia the BOM could be interpreted as a regular char. So I'm unsure if your fix is good.

Many thanks for the incredible fast response.

**Comment by danielfernandez** [comment]
> As far as I understand the BOM is only the first byte, so there is no need to check it everywhere. 
> As I understand a check everywhere could have side effects. Following the German Wikipedia 
> the BOM could be interpreted as a  regular char. So I'm unsure if your fix is good.

Once the stream is converted to chars, BOM symbols should be interpreted as zero-size whitespaces, which basically means they should be ignored. 

The purpose of that symbol is the correct auto-configuration of unicode character input streams, and as thymeleaf output (result) is a different document than input (template) --created by different output writers-- in my opinion it makes no sense to let the BOM symbol pass on to the output document. I think ignoring them altogether should be the better option.

**Comment by opensource21** [comment]
Didn't find a clear definition how to handle it. In BOMInputStream.java I think only the first bytes are handled as BOM. However I don't think that it will have any influence on behavior only the performance will be a little bit better if you only check the first bytes.
