### ISSUE TITLE
Hard dependency on OGNL + javassist for Non-StandardDialect

### ISSUE THREAD

**Issue by zimmi** [thymeleaf/thymeleaf#235]
In thymeleaf-spring version 2.1.0-beta2 it was possible to remove the dependencies on javassist and OGNL because the StandardDialect was not used:

```
<dependency>
    <groupId>org.thymeleaf</groupId>
    <artifactId>thymeleaf-spring3</artifactId>
    <version>2.1.0-beta2</version>

    <!-- Since we use SpEL, OGNL is not needed. -->
    <exclusions>
        <exclusion>
            <artifactId>ognl</artifactId>
            <groupId>ognl</groupId>
        </exclusion>
        <exclusion>
            <artifactId>javassist</artifactId>
            <groupId>org.javassist</groupId>
        </exclusion>
    </exclusions>
</dependency>
```

In 2.1.0.RELEASE that's no longer possible.

Excluding OGNL and javassist as seen above leads to:

```
Caused by: 
java.lang.ClassNotFoundException: javassist.ClassPath
    at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:244)
    at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:230)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:429)
    at org.eclipse.jetty.webapp.WebAppClassLoader.loadClass(WebAppClassLoader.java:382)
    at org.thymeleaf.standard.StandardDialect.<init>(StandardDialect.java:453)
    at org.thymeleaf.spring3.dialect.SpringStandardDialect.<init>(SpringStandardDialect.java:421)
    at org.thymeleaf.spring3.SpringTemplateEngine.<clinit>(SpringTemplateEngine.java:68)
```

Only excluding OGNL leads to:

```
Caused by: 
java.lang.NoClassDefFoundError: ognl/OgnlException
    at org.thymeleaf.standard.StandardDialect.<init>(StandardDialect.java:453)
    at org.thymeleaf.spring3.dialect.SpringStandardDialect.<init>(SpringStandardDialect.java:421)
    at org.thymeleaf.spring3.SpringTemplateEngine.<clinit>(SpringTemplateEngine.java:68)
```

Something similiar was once fixed for issue #137. I would argue that keeping javassist and OGNL optional removes dependency issues for users.

**Comment by danielfernandez** [comment]
Initialization code for `StandardDialect` was making a reference to `OGNLVariableExpressionEvaluator` even before it was decided whether this was needed or not (because of the presence of Spring). Should now be fixed.

Updated 2.1.2-SNAPSHOT

**Comment by zimmi** [comment]
That's great, thank you so much. :)
