### ISSUE TITLE
StackOverflow error with preprocessing expression

### ISSUE THREAD

**Issue by jmiguelsamper** [thymeleaf/thymeleaf#244]
I've come to a preprocessing parsing error.

Given a context attribute with value `1--1`, for example

``` java
    model.addAttribute("crashme", "1--1");
```

and a `th:href` expression like

``` html
    <a th:href="@{__${crashme}__}">Go!</a>
```

the following exception is raised

```
    SEVERE: Servlet.service() for servlet [SpringServlet] in context with 
    path [/] threw exception [Handler processing failed; nested exception
    is java.lang.StackOverflowError] with root cause
        java.lang.StackOverflowError
    at org.thymeleaf.standard.expression.Token.isTokenChar(Token.java:111)
    at org.thymeleaf.standard.expression.Token.isTokenChar(Token.java:128)
    at org.thymeleaf.standard.expression.Token.isTokenChar(Token.java:111)
    at org.thymeleaf.standard.expression.Token.isTokenChar(Token.java:128)
    at org.thymeleaf.standard.expression.Token.isTokenChar(Token.java:111)
    ...
```

**Comment by jmiguelsamper** [comment]
Tested on 2.1.1

**Comment by danielfernandez** [comment]
Updated 2.1.2-SNAPSHOT
