### ISSUE TITLE
Simple select throws 

### ISSUE THREAD

**Issue by inkrement** [thymeleaf/thymeleaf#337]
I try to generate a simple form including a select-box. I used a static value-attribute for debugging purposes but the following example throws a ParseException. I am not sure how to interpret this error message.

How to set the AbstractNumberFormat and why isn't thymeleaf able to parse "1"?!

```
<select class="form-control" th:field="*{itemTypeId}" id="itemType">
    <option th:each="type : ${itemTypes}" th:value="1" >Someoption</option>
</select>
```

```
Error during execution of processor 'org.thymeleaf.spring4.processor.attr.SpringOptionFieldAttrProcessor' (backend/item/createForm)] with root cause

java.text.ParseException: 1
    at org.springframework.format.number.AbstractNumberFormatter.parse(AbstractNumberFormatter.java:58)
    at org.springframework.format.number.CurrencyFormatter.parse(CurrencyFormatter.java:80)
    at org.springframework.format.number.CurrencyFormatter.parse(CurrencyFormatter.java:42)
    at org.springframework.format.support.FormattingConversionService$ParserConverter.convert(FormattingConversionService.java:183)
    at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:35)
    at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:174)
    at org.springframework.core.convert.support.ConvertingPropertyEditorAdapter.setAsText(ConvertingPropertyEditorAdapter.java:59)
    at org.springframework.web.servlet.tags.form.SelectedValueComparator.exhaustiveCompare(SelectedValueComparator.java:173)
    at org.springframework.web.servlet.tags.form.SelectedValueComparator.isSelected(SelectedValueComparator.java:98)
    at org.springframework.web.servlet.tags.form.SelectedValueComparatorWrapper.isSelected(SelectedValueComparatorWrapper.java:34)
    at org.thymeleaf.spring4.processor.attr.SpringOptionFieldAttrProcessor.doProcess(SpringOptionFieldAttrProcessor.java:68)
    at org.thymeleaf.spring4.processor.attr.AbstractSpringFieldAttrProcessor.processAttribute(AbstractSpringFieldAttrProcessor.java:103)
    at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:87)
    at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
    at org.thymeleNode.applyNextProcessor(Node.java:1016)
...
```

**Comment by danielfernandez** [comment]
Maybe your `itemTypeId` field has some kind of custom formatter like a `@NumberFormat` annotation or similar? Perhaps that `1`, even being a valid number, would not be a valid rendering of that field... (for example, if you require decimals, or a sign symbol...)
