### ISSUE TITLE
3.0-dev branch  java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ubala** [thymeleaf/thymeleaf#360]
Created local snapshot and failed on performance test.

org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing ("templates/stocks.thymeleaf.html")
    at org.thymeleaf.aurora.parser.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:168)
    at org.thymeleaf.aurora.parser.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:84)
    at org.thymeleaf.aurora.TemplateEngine.process(TemplateEngine.java:206)
    at org.thymeleaf.TemplateEngine.processTemplate2(TemplateEngine.java:1236)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1075)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1026)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:970)
    at com.mitchellbosecke.benchmark.Thymeleaf.benchmark(Thymeleaf.java:33)
    at com.mitchellbosecke.benchmark.generated.Thymeleaf_benchmark.benchmark_thrpt_jmhStub(Thymeleaf_benchmark.java:116)
    at com.mitchellbosecke.benchmark.generated.Thymeleaf_benchmark.benchmark_Throughput(Thymeleaf_benchmark.java:69)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:455)
    at org.openjdk.jmh.runner.BenchmarkHandler$BenchmarkTask.call(BenchmarkHandler.java:437)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
Caused by: org.attoparser.ParseException: 4
    at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:402)
    at org.attoparser.MarkupParser.parse(MarkupParser.java:266)
    at org.thymeleaf.aurora.parser.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:145)
    ... 19 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 4
    at org.thymeleaf.aurora.engine.ProcessorIterator$InternalEngineProcessorIterator.next(ProcessorIterator.java:131)
    at org.thymeleaf.aurora.engine.ProcessorIterator.next(ProcessorIterator.java:68)
    at org.thymeleaf.aurora.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:443)
    at org.thymeleaf.aurora.engine.TemplateHandlerAdapterMarkupHandler.handleOpenElementEnd(TemplateHandlerAdapterMarkupHandler.java:282)
    at org.attoparser.AbstractChainedMarkupHandler.handleOpenElementEnd(AbstractChainedMarkupHandler.java:251)
    at org.thymeleaf.aurora.parser.AbstractMarkupTemplateParser$ThymeleafMarkupHandler.handleOpenElementEnd(AbstractMarkupTemplateParser.java:737)
    at org.attoparser.HtmlElement.handleOpenElementEnd(HtmlElement.java:109)
    at org.attoparser.HtmlMarkupHandler.handleOpenElementEnd(HtmlMarkupHandler.java:311)
    at org.attoparser.MarkupEventProcessor.processOpenElementEnd(MarkupEventProcessor.java:445)
    at org.attoparser.ParsingElementMarkupUtil.parseOpenElement(ParsingElementMarkupUtil.java:141)
    at org.attoparser.MarkupParser.parseBuffer(MarkupParser.java:719)
    at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:310)
    ... 21 more

**Comment by danielfernandez** [comment]
The 3.0-dev branch is still under heavy development. And I really mean _heavy_ ;)
So don't worry about these kinds of things yet. It's just the engine isn't still complete. I'm somewhat surprised it did just fail the tests and not explode or something ;)
