### ISSUE TITLE
org.xml.sax.SAXException: Scanner State 24 not Recognized 

### ISSUE THREAD

**Issue by acr92** [thymeleaf/thymeleaf#37]
After upgrading to Thymeleaf 2.0.10 from 2.0.8 I started getting this exception, which was not very clear, it turns out however that it was caused when my layout file didn't start directly with <!DOCTYPE .... >. If I have a space, or a new line before that, then it would result in this. Now, I know HTML dictates that the document should start with <!DOCTYPE..., so why this worked before I don't know, but in any case I think providing a better error message to the end user would be very helpful. Something along the lines of "It was not possible to parse the document, does it start with <!DOCTYPE?" or similar.

org.xml.sax.SAXException: Scanner State 24 not Recognized 
at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1250)
at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:568)
at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:302)
at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.doParse(AbstractNonValidatingSAXTemplateParser.java:183)
at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplateUsingPool(AbstractNonValidatingSAXTemplateParser.java:115)
at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.parseTemplate(AbstractNonValidatingSAXTemplateParser.java:96)
at org.thymeleaf.TemplateRepository.getTemplate(TemplateRepository.java:276)
at org.thymeleaf.fragment.FragmentAndTarget.extractFragment(FragmentAndTarget.java:76)
at org.thymeleaf.processor.attr.AbstractFragmentHandlingAttrProcessor.processAttribute(AbstractFragmentHandlingAttrProcessor.java:71)
at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:74)
at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
at org.thymeleaf.dom.Node.applyNextProcessor(Node.java:809)
at org.thymeleaf.dom.Node.processNode(Node.java:771)
at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:626)
at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:608)
at org.thymeleaf.dom.Node.processNode(Node.java:789)
at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:626)
at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:608)
at org.thymeleaf.dom.Node.processNode(Node.java:789)
at org.thymeleaf.dom.Document.process(Document.java:90)
at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1233)
at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1145)
at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1090)
at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1003)
at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:977)
at XXX.http.results.RenderTemplate.getOutputData(RenderTemplate.java:79)
at XXX.http.results.Response.render(Response.java:70)
at XXX.http.WebserverInvoker.writeDynamicMethod(WebserverInvoker.java:270)
at XXX.http.WebserverInvoker.invokeMethod(WebserverInvoker.java:163)
at XXX.http.WebserverInvoker.invoke(WebserverInvoker.java:106)
at XXX.http.WebserverHandler.messageReceived(WebserverHandler.java:81)
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:351)
at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:552)
at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:431)
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:354)
at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:336)
at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:209)
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:354)
at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:336)
at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:209)
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:94)
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.processSelectedKeys(AbstractNioWorker.java:372)
at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:246)
at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:38)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
at java.lang.Thread.run(Thread.java:722)

**Comment by danielfernandez** [comment]
This is a bug. The new THYMELEAF_ROOT element, added in 2.0.9 (which is a synthetic markup element inserted in order to allow Thymeleaf process templates with no root element / several root elements) was being inserted before the DOCTYPE (and not after) when there were whitespaces or comments before the DOCTYPE --which anyway is something that should never happen because some browsers would not correctly read it. 

Fixed in 2.0.11-SNAPSHOT.
