### ISSUE TITLE
keep (custom) IContext accessible

### ISSUE THREAD

**Issue by oliverlietz** [thymeleaf/thymeleaf#388]
The `IContext` supplied to `ITemplateEngine#process(...)`should be kept fully accessible in downstream workers, e.g.:
- `IElementProcessor#process(...)`
- `IResourceResolver#resolveResource(...)`
- `ITemplateResolver#resolveTemplate(...)`
- `IMessageResolver#resolveMessage(...)`

It is the only convenient way to pass in and use required objects/services.

https://sling.apache.org/documentation/bundles/scripting/scripting-thymeleaf.html

**Comment by oliverlietz** [comment]
```
An error happened during template parsing (template: "/apps/fling/page/simple/html.html") (500)

The requested URL /fling.html resulted in an error in /apps/fling/page/simple/html.html.

Exception:

org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "/apps/fling/page/simple/html.html")
    at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:209)
    at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parseStandalone(AbstractMarkupTemplateParser.java:96)
    at org.thymeleaf.engine.TemplateManager.processResolvedResource(TemplateManager.java:794)
    at org.thymeleaf.engine.TemplateManager.processTemplate(TemplateManager.java:669)
    at org.thymeleaf.engine.TemplateManager.processStandaloneTemplate(TemplateManager.java:534)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1117)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:996)
    at org.apache.sling.scripting.thymeleaf.internal.ThymeleafScriptEngine.eval(ThymeleafScriptEngine.java:204)
    at org.apache.sling.scripting.core.impl.DefaultSlingScript.call(DefaultSlingScript.java:389)
    at org.apache.sling.scripting.core.impl.DefaultSlingScript.eval(DefaultSlingScript.java:185)
    at org.apache.sling.scripting.core.impl.DefaultSlingScript.service(DefaultSlingScript.java:492)
    at org.apache.sling.engine.impl.request.RequestData.service(RequestData.java:533)
    at org.apache.sling.engine.impl.filter.SlingComponentFilterChain.render(SlingComponentFilterChain.java:44)
    at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
    at org.apache.sling.engine.impl.SlingRequestProcessorImpl.processComponent(SlingRequestProcessorImpl.java:282)
    at org.apache.sling.engine.impl.filter.RequestSlingFilterChain.render(RequestSlingFilterChain.java:49)
    at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:77)
    at org.apache.sling.i18n.impl.I18NFilter.doFilter(I18NFilter.java:129)
    at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
    at org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter.doFilter(RequestProgressTrackerLogFilter.java:95)
    at org.apache.sling.engine.impl.filter.AbstractSlingFilterChain.doFilter(AbstractSlingFilterChain.java:68)
    at org.apache.sling.engine.impl.SlingRequestProcessorImpl.doProcessRequest(SlingRequestProcessorImpl.java:151)
    at org.apache.sling.engine.impl.SlingMainServlet.service(SlingMainServlet.java:217)
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
    at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:70)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
    at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:267)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
    at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:80)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
    at org.eclipse.jetty.server.Server.handle(Server.java:497)
    at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
    at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
    at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.attoparser.ParseException: Cannot handle context: org.thymeleaf.context.WebVariablesMap (template: "/apps/fling/page/simple/html.html" - line 21, col 7)
    at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:393)
    at org.attoparser.MarkupParser.parse(MarkupParser.java:257)
    at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:201)
    ... 43 more
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Cannot handle context: org.thymeleaf.context.WebVariablesMap (template: "/apps/fling/page/simple/html.html" - line 21, col 7)
    at org.apache.sling.scripting.thymeleaf.internal.SlingResourceResolver.resolveResource(SlingResourceResolver.java:80)
    at org.thymeleaf.engine.TemplateManager.resolve(TemplateManager.java:725)
    at org.thymeleaf.engine.TemplateManager.parseFragment(TemplateManager.java:453)
    at org.thymeleaf.engine.TemplateManager.parseStandaloneFragment(TemplateManager.java:363)
    at org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor.doProcess(AbstractStandardFragmentInsertionTagProcessor.java:115)
    at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:76)
    at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:100)
    at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1565)
    at org.thymeleaf.engine.TemplateHandlerAdapterMarkupHandler.handleOpenElementEnd(TemplateHandlerAdapterMarkupHandler.java:337)
    at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler$InlineMarkupAdapterHandler.handleOpenElementEnd(InlinedOutputExpressionMarkupHandler.java:281)
    at org.thymeleaf.standard.inline.OutputExpressionInlineHandler.handleOpenElementEnd(OutputExpressionInlineHandler.java:197)
    at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler.handleOpenElementEnd(InlinedOutputExpressionMarkupHandler.java:127)
    at org.attoparser.HtmlElement.handleOpenElementEnd(HtmlElement.java:109)
    at org.attoparser.HtmlMarkupHandler.handleOpenElementEnd(HtmlMarkupHandler.java:297)
    at org.attoparser.MarkupEventProcessorHandler.handleOpenElementEnd(MarkupEventProcessorHandler.java:402)
    at org.attoparser.ParsingElementMarkupUtil.parseOpenElement(ParsingElementMarkupUtil.java:159)
    at org.attoparser.MarkupParser.parseBuffer(MarkupParser.java:710)
    at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:301)
    ... 45 more
Request Progress:

      0 TIMER_START{Request Processing}
      0 COMMENT timer_end format is {<elapsed msec>,<timer name>} <optional message>
      0 LOG Method=GET, PathInfo=/fling.html
      0 TIMER_START{ResourceResolution}
     12 TIMER_END{12,ResourceResolution} URI=/fling.html resolves to Resource=JcrNodeResource, type=fling/page/simple, superType=null, path=/content/fling
     13 LOG Resource Path Info: SlingRequestPathInfo: path='/content/fling', selectorString='null', extension='html', suffix='null'
     13 TIMER_START{ServletResolution}
     13 TIMER_START{resolveServlet(JcrNodeResource, type=fling/page/simple, superType=null, path=/content/fling)}
     29 TIMER_END{16,resolveServlet(JcrNodeResource, type=fling/page/simple, superType=null, path=/content/fling)} Using servlet /apps/fling/page/simple/html.html
     30 TIMER_END{17,ServletResolution} URI=/fling.html handled by Servlet=/apps/fling/page/simple/html.html
     30 LOG Applying Requestfilters
     30 LOG Calling filter: org.apache.sling.engine.impl.debug.RequestProgressTrackerLogFilter
     30 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
     31 LOG Applying Componentfilters
     31 TIMER_START{/apps/fling/page/simple/html.html#0}
    314 LOG SCRIPT ERROR: org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "/apps/fling/page/simple/html.html")
    314 TIMER_END{283,/apps/fling/page/simple/html.html#0}
    315 LOG Filter timing: filter=org.apache.sling.i18n.impl.I18NFilter, inner=283, total=284, outer=1
    316 LOG Applying Error filters
    316 LOG Calling filter: org.apache.sling.i18n.impl.I18NFilter
    316 TIMER_START{handleError:throwable=org.thymeleaf.exceptions.TemplateInputException}
    322 TIMER_END{6,handleError:throwable=org.thymeleaf.exceptions.TemplateInputException} Using handler org.apache.sling.servlets.resolver.internal.defaults.DefaultErrorHandlerServlet
    335 TIMER_END{335,Request Processing} Dumping SlingRequestProgressTracker Entries
```

**Comment by danielfernandez** [comment]
Please have a look at the new Template Resolution (#419), Context (#420) and Message Resolution (#421) APIs.

It is now possible to make the engine use a custom implementation of the _context_ passed as a parameter to `ITemplateEngine#process(...)`, as long as such context implements the `IEngineContext` interface. But this is _strongly not recommended_ except in very rare occasions, due to the high complexity of `IEngineContext`, needed in order for the template engine to correctly keep its status at any time.

Please make sure you really need to create such _custom context_ implementation. Note that it is possible to add _expression objects_ to be used in expressions (such as `${#myObject}` by simply adding them to custom dialects (see #401). If what you need are certain objects/services that should be made available to all your processors or pre-/post-processors, those are called _execution attributes_, and can also be provided by dialects (again, see #401).

As for the specific methods you mention, note `IResourceResolver` has been removed completely (see #419) and that the `ITemplateResolver#resolveTemplate(...)` method no longer receives any type of context as argument (see https://github.com/thymeleaf/thymeleaf/blob/a3c688f35379660320ae9378a849b0a13c08a295/src/main/java/org/thymeleaf/templateresolver/ITemplateResolver.java#L97-L121). The reason for the latter is that template resolution will only happen once for cached templates, even if those templates will afterwards be executed from cache using many other different contexts. Templates could therefore be resolved using variables that will no longer exist in subsequent executions, which is a potential data coherence problem.

**Comment by danielfernandez** [comment]
I'm closing this for now, unless you consider there are additional problems in the current implementations of these template resolution, message resolution and context APIs that need further discussion. Thanks.
