### ISSUE TITLE
Invocation of #fields.hasErrors() fails to NPE.

### ISSUE THREAD

**Issue by akarandii** [thymeleaf/thymeleaf#433]
"fields" object is not null and true/false result is expected, but invocation fails with:

org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "#fields.hasErrors()" (/registration/form:9)
    at org.thymeleaf.spring4.expression.SpelVariableExpressionEvaluator.evaluate(SpelVariableExpressionEvaluator.java:161) ~[thymeleaf-spring4-2.1.4.RELEASE.jar:2.1.4.RELEASE]
......
Caused by: java.lang.NullPointerException: null
    at org.thymeleaf.spring4.util.FieldUtils.checkErrors(FieldUtils.java:245) ~[thymeleaf-spring4-2.1.4.RELEASE.jar:2.1.4.RELEASE]

[Spring 4.2.2, Thymeleaf 2.1.4, JDK 1.8.0_60]

**Comment by akarandii** [comment]
Sorry, i missed to bound expression with tag contains th:object
