### ISSUE TITLE
autofocus attribute for element Input not supported?

### ISSUE THREAD

**Issue by mmoayyed** [thymeleaf/thymeleaf#474]
```
org.xml.sax.SAXParseException: Attribute name "autofocus" associated with an element type "input" must be followed by the ' = ' character.
    at org.apache.xerces.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.util.ErrorHandlerWrapper.fatalError(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanAttribute(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.XMLParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.apache.xerces.jaxp.SAXParserImpl.parse(Unknown Source) ~[xercesImpl-2.11.0.jar:?]
    at org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser.doParse(AbstractNonValidatingSAXTemplatePar
```

**Comment by mmoayyed** [comment]
Reference http://www.w3schools.com/tags/att_input_autofocus.asp

**Comment by yvanavermaet** [comment]
@mmoayyed 
You should write autofocus="true". 
Eventhough the value is not necessary, it is for Thymeleaf.

**Comment by danielfernandez** [comment]
As @yvanavermaet explained, Thymeleaf 2.1's parser is an XML one, so it requires your attribute to have a value. `autofocus` is a _boolean_ attribute, so the correct way to express its value is `autofocus="autofocus"`, but `autofocus="true"` would work too.

Als note that Thymeleaf 3.0 changes this, as its new parser is not XML anymore, and allows attributes without a value.

**Comment by yhojann-cl** [comment]
In standard from W3C https://www.w3.org/wiki/HTML5_form_additions#autofocus autofocus canot contain boolean value, if you write autofocus="true" canot pass validator. The parser force to break the html5 standard.
