### ISSUE TITLE
Thymeleaf 3, Spring 4  and LayoutDialect

### ISSUE THREAD

**Issue by simonissime** [thymeleaf/thymeleaf#480]
Hello,

sorry in advance for my poor english. I'm getting a try to spring and thymeleaf with the Thymeleaf 3 and Spring 4 tutorial Hello World example.

Here is the dependencies excerpt from my gradle build : 

dependencies {
   compile("commons-logging:commons-logging:1.2")
   compile("javax:javaee-web-api:7.0")
   compile("org.springframework:spring-context-support:4.2.2.RELEASE")
   compile("org.springframework:spring-webmvc:4.2.2.RELEASE")
   compile("org.thymeleaf:thymeleaf:3.0.0.BETA02")
   compile("org.thymeleaf:thymeleaf-spring4:3.0.0.BETA02")
   compile("nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect:1.3.3")
}

The tutorial work fine, but if i want to add layout dialect : 

private TemplateEngine templateEngine() {
        SpringTemplateEngine engine = new SpringTemplateEngine();
        engine.setTemplateResolver(templateResolver());
        //this line breaks all
        engine.addDialect(new LayoutDialect());
        return engine;
    }

I get this : 
29-Mar-2016 18:09:25.225 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.loadOnStartup Servlet [dispatcher] in web application [/tuto-s4-t3-hello] threw load() exception
 java.lang.ClassNotFoundException: org.thymeleaf.dom.Attribute
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1308)
    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1142)
    at nz.net.ultraq.thymeleaf.LayoutDialect.<clinit>(LayoutDialect.groovy:50)
    at com.thymeleafexamples.thymeleaf3.config.ThymeleafConfig.templateEngine(ThymeleafConfig.java:48)
    at com.thymeleafexamples.thymeleaf3.config.ThymeleafConfig.viewResolver(ThymeleafConfig.java:39)
    at com.thymeleafexamples.thymeleaf3.config.ThymeleafConfig$$EnhancerBySpringCGLIB$$7f0645ce.CGLIB$viewResolver$1(<generated>)
    at com.thymeleafexamples.thymeleaf3.config.ThymeleafConfig$$EnhancerBySpringCGLIB$$7f0645ce$$FastClassBySpringCGLIB$$dcc68521.invoke(<generated>)
    at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
    at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:355)
    at com.thymeleafexamples.thymeleaf3.config.ThymeleafConfig$$EnhancerBySpringCGLIB$$7f0645ce.viewResolver(<generated>)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
    at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1123)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1018)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:510)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
    at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
    at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
    at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
    at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
    at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:772)
    at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
    at org.springframework.web.servlet.FrameworkServlet.configureAndRefreshWebApplicationContext(FrameworkServlet.java:667)
    at org.springframework.web.servlet.FrameworkServlet.initWebApplicationContext(FrameworkServlet.java:539)
    at org.springframework.web.servlet.FrameworkServlet.initServletBean(FrameworkServlet.java:493)
    at org.springframework.web.servlet.HttpServletBean.init(HttpServletBean.java:136)
    at javax.servlet.GenericServlet.init(GenericServlet.java:158)
    at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1238)
    at org.apache.catalina.core.StandardWrapper.load(StandardWrapper.java:1041)
    at org.apache.catalina.core.StandardContext.loadOnStartup(StandardContext.java:4997)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5289)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
    at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
    at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
    at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
    at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:939)
    at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1812)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

Some hints ?

**Comment by jmiguelsamper** [comment]
Hello,

unfortunately, the LayoutDialect is not yet compatible with Thymeleaf 3.

It will be soon, hopefully.

Kind regards,
 Zemi
