### ISSUE TITLE
There is no method which named init in Object org.thymeleaf.dom.Text,but when use with springboot,an exception is throwed.

### ISSUE THREAD

**Issue by Kumilo** [thymeleaf/thymeleaf#483]
## below is  the detail.

org.springframework.web.util.NestedServletException: Handler processing failed; nested exception is java.lang.NoSuchMethodError: org.thymeleaf.dom.Text.<init>(Ljava/lang/String;Ljava/lang/String;Ljava/lang/Integer;Z)V
    at org.springframework.web.servlet.DispatcherServlet.triggerAfterCompletionWithError(DispatcherServlet.java:1303) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:977) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:893) ~[spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970) [spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861) [spring-webmvc-4.2.3.RELEASE.jar:4.2.3.RELEASE]
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:622) [servlet-api.jar:na]

**Comment by danielfernandez** [comment]
It looks like you are trying to use Spring Boot with Thymeleaf 3.0. In Thymeleaf 3.0 the `org.thymeleaf.dom.Text` class does not exist anymore.

Spring Boot has not yet been adapted to Thymeleaf 3.0, they'll probably wait until Thymeleaf 3.0 goes GA (which makes sense). There's nothing that can be done from this side, sorry...
