### ISSUE TITLE
StackOverflowError when inserting content before first element of model

### ISSUE THREAD

**Issue by MartinW79** [thymeleaf/thymeleaf#653]
We have a processor created (extending AbstractAttributeModelProcessor) that responds to y:noIndex attribute. 

```html
<div y:noIndex>
   <some body elements>
</div>
```

The task is to add comments before and after the complete model body for the Google Search Appliance to turn off indexing for these contents. 

Desired result: 

```html
<!-- googleoff: index -->
<div>
   <some body elements>
</div>
<!-- googleon: index -->
```

In order to get access to full body (OpenElement till CloseElement) we created an AttributeModelProcessor. 

Adding a comment behind the CloseElement was simple: 

```java
model.add(modelFactory.createComment("googleon: index"));
```

We thought it would be also as simple to insert a new comment at the beginning. 

```java
model.insert(0, modelFactory.createComment("googleoff: index"));
```

But with this we run into StackOverflowError! 
The stacktrace is showing approx. 1000 line with the following messages repeated again and again 

```
        at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78) 
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) 
        at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) 
        at org.thymeleaf.engine.Model.process(Model.java:282) 
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) 
        at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) 
        at org.thymeleaf.engine.Model.process(Model.java:282) 
        at org.thymeleaf.engine.Model.process(Model.java:290) 
        at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78) 
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640) 
        at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139) 
        at org.thymeleaf.engine.Model.process(Model.java:282) 
        at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587) 
        at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205) 
        at org.thymeleaf.engine.Model.process(Model.java:282) 
        at org.thymeleaf.engine.Model.process(Model.java:290) 
        at org.thymeleaf.engine.GatheringModelProcessable.process(GatheringModelProcessable.java:78) 
```

As discussed in thymeleaf forum [(link)](http://forum.thymeleaf.org/StackOverflowError-when-editing-model-td4030717.html) this is because we are signaling at the constructor that the matched attribute should be removed afterwards.

But with adding an additional element before the first ( insert at position 0 ), the "removeAttribute" flag is triggering the attribute removal on the first element in the modified model. By the time it does that --after execution--, such "first element" has been modified because you've inserted a comment at the beginning. 

It works perfectly fine when removing the element manually in doProcess() method.

**Comment by danielfernandez** [comment]
Already in `3.0.10-SNAPSHOT`
