### ISSUE TITLE
SpringEL after upgrades since 2.1.4 to 3.0.9 thymeleaf

### ISSUE THREAD

**Issue by dredintellekt** [thymeleaf/thymeleaf#718]
Hello there.

We have some inexplicable issue.

On the thymeleaf 2.14 / 2.16 we haven`t that error but on the 3.00 /3.09/3.0.10 we have that one.
We work with servicemix 3.11 version and spring 3+.

After updating our dependecies to 3+ version of thymeleaf we get that error :

Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "formFactors" (template: "admin/adminProductEdit" - line 158, col 37)

on that and next lines in html file we have

                        th:each="formFactor,iterStat : *{formFactors}"
                        th:id="*{'formLi-'+ formFactors[__${iterStat.index}__].id}">
                                          ..........

These lines just show formFactor of products on the web page, it`s 1 of the some parametrs of product

We have (Page 1), web page where we can create newTemplate of our product.
(Page 2) where  we can look or change current template of our products.
To raise this error It needs to open Page 1 and than when we open Page 2 we see that error. If we open only Page 2 and other pages which don`t go into base and don`t do anything with formFactor it works well.

I repeat, that only if we change our dependencies since

thymeleaf/3.0.9-SNAPSHOT
thymeleaf-spring3/3.0.9-SNAPSHOT
thymeleaf-extras-springsecurity3/3.0.2-SNAPSHOT

to

thymeleaf/2.1.4-SNAPSHOT
thymeleaf-spring3/2.1.4-SNAPSHOT
thymeleaf-extras-springsecurity3/2.1.2-SNAPSHOT

for example, it works well. But we need thymeleaf 3+

**Comment by danielfernandez** [comment]
Could you copy the entire exception message (ideally the trace), or at least see if there is a nested exception? the Spring EL engine should be outputting a nested exception which should better explain specifically what it does not like...

**Comment by dredintellekt** [comment]
It is strange but the line of error changed to 93, but doesn`t matter. It worked before. 
The line 93 is
       th:value="*{product.id}"/>

Now, we have 

thymeleaf/3.0.10.RELEASE
thymeleaf-spring3/3.0.10.RELEASE
thymeleaf-extras-springsecurity3/3.0.3.RELEASE


Error is

----


Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating SpringEL expression: "product.id" (template: "admin/adminProductEdit" - line 93, col 64)
    at org.thymeleaf.spring3.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:245)
    at org.thymeleaf.standard.expression.SelectionVariableExpression.executeSelectionVariableExpression(SelectionVariableExpression.java:158)
    at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:92)
    at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109)
    at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138)
    at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:144)
    at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
    at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
    at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
    at org.thymeleaf.engine.ProcessorTemplateHandler.handleStandaloneElement(ProcessorTemplateHandler.java:918)
    at org.thymeleaf.engine.StandaloneElementTag.beHandled(StandaloneElementTag.java:228)
    at org.thymeleaf.engine.Model.process(Model.java:282)
    at org.thymeleaf.engine.Model.process(Model.java:290)
    at org.thymeleaf.engine.IteratedGatheringModelProcessable.processIterationModel(IteratedGatheringModelProcessable.java:367)
    at org.thymeleaf.engine.IteratedGatheringModelProcessable.process(IteratedGatheringModelProcessable.java:221)
    at org.thymeleaf.engine.ProcessorTemplateHandler.handleCloseElement(ProcessorTemplateHandler.java:1640)
    at org.thymeleaf.engine.CloseElementTag.beHandled(CloseElementTag.java:139)
    at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136)
    at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:592)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098)
    at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1072)
    at org.thymeleaf.spring3.view.ThymeleafView.renderFragment(ThymeleafView.java:361)
    at org.thymeleaf.spring3.view.ThymeleafView.render(ThymeleafView.java:193)
    at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1216)
    at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1001)
    at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:945)
    at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:867)
    at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:953)
    ... 75 more
Caused by: java.lang.ClassCastException: com.isbc.configurator.core.util.forms.ProductTypeSaveForm cannot be cast to java.util.Map
    at org.springframework.context.expression.MapAccessor.read(MapAccessor.java:46)
    at org.springframework.expression.spel.ast.PropertyOrFieldReference.readProperty(PropertyOrFieldReference.java:177)
    at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:85)
    at org.springframework.expression.spel.ast.PropertyOrFieldReference.getValueInternal(PropertyOrFieldReference.java:78)
    at org.springframework.expression.spel.ast.CompoundExpression.getValueRef(CompoundExpression.java:49)
    at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:82)
    at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:93)
    at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:94)
    at org.thymeleaf.spring3.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:218)
    ... 102 more

**Comment by danielfernandez** [comment]
Two questions: are you using Spring Boot or _vanilla_ Spring Framework? in any case, what version? (of Spring Boot or Spring Framework). I see it looks like Spring 3 but I want confirmation.

The SpEL compiler in some specific versions of Spring 3.x did not gracefully retry the application of compiled SpEL expressions when they were applied to objects of different types than, for example, in a previous page (for example, maybe your `product` variable in some other page is a Map). In such case, disabling SpEL compiler (you can do it at the `SpringStandardDialect` or the `SpringTemplateEngine`) will fix the issue, but it would be a better option if you could update your version of Spring Framework to the latest update (x.y.UPDATE) in your x.y version.

**Comment by dredintellekt** [comment]
Yes, we use spring framework, not boot.

Is it possible to switch off SpEL, because we rewrote that SpEL when we found bugs and work with our code?
Since we used to ServiceMix we have different version of bundles and other libraries, so we use Spring versions since  3.2.10 till 3.2.4.RELEASE

**Comment by danielfernandez** [comment]
>Is it possible to switch off SpEL

Not SpEL, but the SpEL compiler that appeared in Spring 3.1. It compiles SpEL expressions to bytecode for better performance.

**Comment by dredintellekt** [comment]
But, anyway, we use Spring 3.2+ . Which version of Spring in 3rd major version is better?

**Comment by dredintellekt** [comment]
And, there is some strange fact.
If we make this error in evening, before the way home, then error gone on the morning, when we come. It looks like some cache in the system which handles our code

**Comment by dredintellekt** [comment]
I found, that while we haven`t exception, in MapAccessor as target we can found SPEL Context and name of variable is "iterStat" as in line 158. 


![noexc](https://user-images.githubusercontent.com/18497114/47215483-41677380-d3aa-11e8-867c-54f72999baf0.jpg)



If we reproduce exception,we can found as target our class ProductTypeSaveFrom with name "formFactor' 



![hasexc](https://user-images.githubusercontent.com/18497114/47215497-47f5eb00-d3aa-11e8-9c96-f948e3a02568.jpg)



Context is the same in both situation. I use one page for that.

**Comment by dredintellekt** [comment]
Hello there, again.
Anyway, is it any way to code this correct? :-)

**Comment by dredintellekt** [comment]
Also, i Found how to genereate Exception everytime

If i add formFactors like 

Controller.class

    List formFactor=getFormFactorById(id);
    model.addAttribute("formFactors",formFactor);



myView.html

                    <li class="is-panel" th:object="${formFactors}">
                        <fieldset class="is-form-horizontal">
                            <div class="is-form-row">
                                <label class="is-form-label">Some name</label>
                                <div class="is-form-controls">
                                    <input id="formFactorMessageType" type="text" th:field="${formFactorTypeMessage}"
                                           required="required"/>
                                </div>
                            </div>
                            <ul class="is-list is-margin-top">
                                <li class="is-panel is-panel-box is-width-1-1 is-margin-top is-margin-bottom"
                                    th:each="formFactor,iterStat : *{formFactors}"
                                    th:id="${'formLi-'+ formFactors[__${iterStat.index}__].id}">


So, I get everytime Exception java.util.ArrayList cannot be cast to java.util.Map in line 

     <li class="is-panel" th:object="${formFactors}">

**Comment by dredintellekt** [comment]
And this issue can be closed, because I found how to solve it.

I added into my Controller 

model.addAttribute("formFactors",formFactor);

and into Template chaged 
th:each="formFactor,iterStat : *{formFactors}"
into 
th:each="formFactor,iterStat : ${formFactors}"

And it works, but i don`t understand how )
