### ISSUE TITLE
A simple problem！

### ISSUE THREAD

**Issue by Hgqin** [thymeleaf/thymeleaf#803]
If I put the html file under WEB-INF, and then define the template under WEB-INF, I keep reporting errors to Java. Io. FILENOTFOUNDEXCEPTION: Could not open ServletContext resource [/WEB-INF/view/user/encomposition-en/common/common. HTML ]
How can I solve this problem at not exchange file location？

```
15-Oct-2020 11:24:57.920 严重 [http-nio-80-exec-2] org.apache.catalina.core.StandardWrapperValve.invoke 在路径为的上下文中，Servlet[app]的Servlet.service（）引发了具有根本原因的异常Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "ServletContext resource [/WEB-INF/view/user/composition-en/practise.html]")
	java.io.FileNotFoundException: Could not open ServletContext resource [/WEB-INF/view/user/encomposition-en/common/common_header.html]
		at org.springframework.web.context.support.ServletContextResource.getInputStream(ServletContextResource.java:159)
		at org.thymeleaf.spring5.templateresource.SpringResourceTemplateResource.reader(SpringResourceTemplateResource.java:103)
		at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:223)
		at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parseStandalone(AbstractMarkupTemplateParser.java:100)
		at org.thymeleaf.engine.TemplateManager.parseStandalone(TemplateManager.java:302)
		at org.thymeleaf.standard.expression.FragmentExpression.resolveExecutedFragmentExpression(FragmentExpression.java:588)
		at org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor.computeFragment(AbstractStandardFragmentInsertionTagProcessor.java:379)
		at org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor.doProcess(AbstractStandardFragmentInsertionTagProcessor.java:110)
		at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
		at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
		at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
		at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314)
		at org.thymeleaf.engine.TemplateHandlerAdapterMarkupHandler.handleOpenElementEnd(TemplateHandlerAdapterMarkupHandler.java:304)
		at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler$InlineMarkupAdapterPreProcessorHandler.handleOpenElementEnd(InlinedOutputExpressionMarkupHandler.java:278)
		at org.thymeleaf.standard.inline.OutputExpressionInlinePreProcessorHandler.handleOpenElementEnd(OutputExpressionInlinePreProcessorHandler.java:186)
		at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler.handleOpenElementEnd(InlinedOutputExpressionMarkupHandler.java:124)
		at org.attoparser.HtmlElement.handleOpenElementEnd(HtmlElement.java:109)
		at org.attoparser.HtmlMarkupHandler.handleOpenElementEnd(HtmlMarkupHandler.java:297)
		at org.attoparser.MarkupEventProcessorHandler.handleOpenElementEnd(MarkupEventProcessorHandler.java:402)
		at org.attoparser.ParsingElementMarkupUtil.parseOpenElement(ParsingElementMarkupUtil.java:159)
		at org.attoparser.MarkupParser.parseBuffer(MarkupParser.java:710)
		at org.attoparser.MarkupParser.parseDocument(MarkupParser.java:301)
		at org.attoparser.MarkupParser.parse(MarkupParser.java:257)
		at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parse(AbstractMarkupTemplateParser.java:230)
		at org.thymeleaf.templateparser.markup.AbstractMarkupTemplateParser.parseStandalone(AbstractMarkupTemplateParser.java:100)
		at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:666)
		at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1098)
		at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1072)
		at org.thymeleaf.spring5.view.ThymeleafView.renderFragment(ThymeleafView.java:362)
		at org.thymeleaf.spring5.view.ThymeleafView.render(ThymeleafView.java:189)
		at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1373)
		at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1118)
		at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1057)
		at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
		at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
		at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
		at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
		at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
		at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
		at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
		at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
		at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
		at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:543)
		at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
		at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)
		at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
		at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
		at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
		at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:615)
		at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
		at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:818)
		at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1626)
		at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
		at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
		at java.lang.Thread.run(Thread.java:745)
```

**Comment by ultraq** [comment]
Given the error message you've posted, the first thing to check would be the paths of the files being processed and if they actually exist at those locations.

It says Thymeleaf is parsing `/WEB-INF/view/user/composition-en/practise.html` but then it can't find a file called `/WEB-INF/view/user/encomposition-en/common/common_header.html`.  The "encomposition-en" directory seems a bit suspicious, like you've got an extra "en" in there that shouldn't be.

**Comment by Hgqin** [comment]
> Given the error message you've posted, the first thing to check would be the paths of the files being processed and if they actually exist at those locations.
> 
> It says Thymeleaf is parsing `/WEB-INF/view/user/composition-en/practise.html` but then it can't find a file called `/WEB-INF/view/user/encomposition-en/common/common_header.html`. The "encomposition-en" directory seems a bit suspicious, like you've got an extra "en" in there that shouldn't be.

You are right！According to your suggestion I rechecked the directory name，I misspelled it.Thanks for getting back to me.
