### ISSUE TITLE
th:text on custom tag gives "already been modified by a previously executed processor"

### ISSUE THREAD

**Issue by xtianus** [thymeleaf/thymeleaf#882]
I don't think this is a bug but might be a feature request, unless I'm doing something wrong.

Thymeleaf version 3.0.14
Spring webmvc 5.3.18

I have created a custom tag like

```
<my:textarea> Content goes here </my:textarea>
```

It works fine unless I make the content dynamic with

```
<my:textarea th:text="${realContent}"> Content goes here </my:textarea>
```

in which case I get this exception before even entering my tag processor:

```
org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "ServletContext resource [/WEB-INF/views/user/editProfile.html]")
[cut]
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Cannot execute model processor org.thymeleaf.util.ProcessorConfigurationUtils$ElementModelProcessorWrapper as the body of the target element has already been modified by a previously executed processor on the same tag. Model processors cannot execute on already-modified bodies as these might contain unprocessable events (e.g. as a result of a 'th:text' or similar) (template: "/user/editProfile" - line 42, col 3)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1485)
	at org.thymeleaf.engine.TemplateHandlerAdapterMarkupHandler.handleOpenElementEnd(TemplateHandlerAdapterMarkupHandler.java:304)
	at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler$InlineMarkupAdapterPreProcessorHandler.handleOpenElementEnd(InlinedOutputExpressionMarkupHandler.java:278)
	at org.thymeleaf.standard.inline.OutputExpressionInlinePreProcessorHandler.handleOpenElementEnd(OutputExpressionInlinePreProcessorHandler.java:186)
	at org.thymeleaf.templateparser.markup.InlinedOutputExpressionMarkupHandler.handleOpenElementEnd(InlinedOutputExpressionMarkupHandler.java:124)
	at org.attoparser.HtmlElement.handleOpenElementEnd(HtmlElement.java:109)
	at org.attoparser.HtmlMarkupHandler.handleOpenElementEnd(HtmlMarkupHandler.java:297)
[cut]
```

The message seems to explain the reason

> Cannot execute model processor org.thymeleaf.util.ProcessorConfigurationUtils$ElementModelProcessorWrapper as the body of the target element has already been modified by a previously executed processor on the same tag. Model processors cannot execute on already-modified bodies as these might contain unprocessable events (e.g. as a result of a 'th:text' or similar)

but it doesn't tell me how to do what I need 8-)

Thank you

**Comment by xtianus** [comment]
To clarify what I'd like to do, I fixed my problem by implementing a custom text tag like so:

```
<my:textarea my:text="${realContent}"> Content goes here </my:textarea>
```

It would be much nicer if I could stick to the standard th attributes instead of rewriting my own:

```
<my:textarea th:text="${realContent}"> Content goes here </my:textarea>
```

**Comment by danielfernandez** [comment]
Given `th:text` also potentially modifies the body of the HTML element, `my:textarea` cannot also modify it.

In order to avoid this, if both behaviours need to be combined it should be my:textarea who allows some other specific parameter be specific for it (e.g. `text` instead of `th:text`) and then read such parameter and process the whole element in one step.
