### ISSUE TITLE
Improve Handling of Template Recursion and Prevent StackOverflowError

### ISSUE THREAD

**Issue by geoffblandrbs** [thymeleaf/thymeleaf#890]
Thymeleaf can cause a `StackOverflowError` if a `th:replace` either directly or indirectly points back to itself.

Whilst this is obviously an coding error in the Thymeleaf template HTML it would be better if this was caught by the Thymeleaf library at some point before a `StackOverflowError` occurs and reported with a more useful exception.

Obviously in some rare situations recursion of the replace method in the template may be OK but it should caught before it recurses to a depth where a `StackOverflowError` would occur.

Example to show the error:

```
<div th:fragment="buttons_recover" th:remove="tag">
  <div th:replace="fragments/routes :: buttons_info"></div>
  <div th:replace="fragments/routes :: buttons_recover"></div> <!-- This causes recusion and a StackOverflowError -->
</div>
```

Exception thrown

```
May 31, 2022 7:29:52 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.StackOverflowError] with root cause
java.lang.StackOverflowError
	....
	at org.thymeleaf.spring5.expression.SPELVariableExpressionEvaluator.evaluate(SPELVariableExpressionEvaluator.java:265)
	at org.thymeleaf.standard.expression.VariableExpression.executeVariableExpression(VariableExpression.java:166)
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:66)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:109)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:138)
	at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:144)
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314)
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
	at org.thymeleaf.engine.Model.process(Model.java:282)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587)
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
	at org.thymeleaf.engine.Model.process(Model.java:282)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587)
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
	at org.thymeleaf.engine.Model.process(Model.java:282)
	...etc, etc...
```

**Comment by geoffblandrbs** [comment]
Thanks for fixing this - we will build with this version when we are able.
