### ISSUE TITLE
regression with 3.1.x - thymyleaf fails to generate urls where servletContext.contextPath != httpServletRequest.contextPath

### ISSUE THREAD

**Issue by tkrah** [thymeleaf/thymeleaf#937]
Hi,

I am using spring boot 3 with thymyleaf 3.1.0 included which fails now to generate urls when a ForwardedHeaderFilter is put in place (to support proxies).
With spring 2.7.x and the included thymyleaf there it is possible to have a servlet context path of "/a" and a HttpServletRequest context path of "/test/a" or "/demo/a" which the proxy does route under that destination to "/a" on the backend.

With boot 3 and thymyleaf 3.1.0 I get this:

```
java.lang.IllegalArgumentException: Cannot build an application for a request which servlet context does not match with the application that it is being built for.
	at org.thymeleaf.util.Validate.isTrue(Validate.java:79) ~[thymeleaf-3.1.0.RELEASE.jar!/:3.1.0.RELEASE]
	at org.thymeleaf.web.servlet.JakartaServletWebApplication.buildExchange(JakartaServletWebApplication.java:64) ~[thymeleaf-3.1.0.RELEASE.jar!/:3.1.0.RELEASE]
	at org.thymeleaf.spring6.view.ThymeleafView.renderFragment(ThymeleafView.java:204) ~[thymeleaf-spring6-3.1.0.RELEASE.jar!/:3.1.0.RELEASE]
	at org.thymeleaf.spring6.view.ThymeleafView.render(ThymeleafView.java:192) ~[thymeleaf-spring6-3.1.0.RELEASE.jar!/:3.1.0.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1414) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
	at org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1158) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1097) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:973) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1003) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:895) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:705) ~[tomcat-embed-core-10.1.1.jar!/:6.0.0]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:880) ~[spring-webmvc-6.0.2.jar!/:6.0.2]
	at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:814) ~[tomcat-embed-core-10.1.1.jar!/:6.0.0]

```

The expectation that the http requests context path must match the servletContext context path does not hold on such proxy + ForwardedHeaderFilter scenarios where the context-path is taken from the "X-Forwarded-Prefix" header.

Can you remove that check or make it configurable to make it optional?

**Comment by tkrah** [comment]
Seems to be the same like:

https://github.com/thymeleaf/thymeleaf/issues/926

Can be closed.
