### ISSUE TITLE
Error resolving template on Server-Sent Events endpoint using Flux

### ISSUE THREAD

**Issue by wimdeblauwe** [thymeleaf/thymeleaf#945]
I have a Spring Boot 2.7.8 application and I have added these dependencies:
```
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
```

My application was already working with `spring-boot-starter-web` and I have added `spring-boot-starter-webflux` so I can return a `Flux<ServerSentEvent>` from a controller method to have support for SSE.

Controller code:
```
    @GetMapping("/transferdatestatuses/updates")
    public Flux<ServerSentEvent<TransferDateStatusesUpdateEvent>> subscribeToTransferDataStatusUpdates() {
        return monitoringSseBroker.subscribeToTaskUpdates()
                                  .map(taskEventList -> ServerSentEvent.<TransferDateStatusesUpdateEvent>builder()
                                                                       .data(TransferDateStatusesUpdateEvent.of(taskEventList))
                                                                       .build());
    }
```

When I just start my application, this works fine. I can connect from the browser on the SSE endpoint and updates are sent. But if I navigate to another page and come back, the browser can no longer connect on the SSE endpoint. The server logging shows:

```
2023-02-01 12:28:07.234 ERROR 4012 --- [nio-8081-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: Error resolving template [transferdatestatuses/updates], template might not exist or might not be accessible by any of the configured Template Resolvers] with root cause

org.thymeleaf.exceptions.TemplateInputException: Error resolving template [transferdatestatuses/updates], template might not exist or might not be accessible by any of the configured Template Resolvers
	at org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.0.15.RELEASE.jar:3.0.15.RELEASE]
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.0.15.RELEASE.jar:3.0.15.RELEASE]
```

It seems as if it does not hit the endpoint of my controller, but for some reason wants to resolve a Thymeleaf template suddenly. Is there any idea what might be wrong? Or where I can debug to help investigate this problem further?

**Comment by wimdeblauwe** [comment]
This was not a Thymeleaf issue. See https://stackoverflow.com/questions/75325758/how-to-combine-sink-asflux-with-server-sent-events-sse-using-spring-webflux for more info on what the issue was.
