### ISSUE TITLE
method parameter containing underscores upsets the pre-processor

### ISSUE THREAD

**Issue by urbancamo** [thymeleaf/thymeleaf#955]
Version: 3.1.1.RELEASE
Environment: Scala SBT Project

I have a Scala Class that provides a number of convenience methods. One method allows you to provide a substitute value as an alternative if a keyed value doesn't exist:

```scala
  def gse(key: String, notExistsValue: String): String = {
    val (actualKey, _) = extractKeyAndCommand(key)
    if (e(actualKey)) {
      gs(actualKey) // return the looked up value
    } else {
      notExistsValue // return the provided value if there is no entry in the data for 'key'
    }
  }
```

One usage is on a form I'm creating - if there is not a value provided in the data then an underscored line is generated so that the value can be handwritten. I call it with the following Thymeleaf expression:

```html
<span th:text='${d.gse("Execution State:LIKE THIS", "____________________")}'>____________________</span>
```

The presence of the underscores upsets the pre-processor because the regular expression `StandardExpressionPreprocessor.PREPROCESS_EVAL` defined as `"\\_\\_(.*?)\\_\\_";` matches on the method parameter containing the underscores.

This causes the exception: 
```
[ERROR] [2023-04-27 11:14:07,896] [main] [o.t.TemplateEngine] - [THYMELEAF][main] Exception processing template "/html/will-latest.html @XML": Could not parse as expression: "" (template: "html/frag/seal" - line 16, col 23) org.thymeleaf.exceptions.TemplateProcessingException: Could not parse as expression: "" (template: "html/frag/seal" - line 16, col 23)
	at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:131)
	at org.thymeleaf.standard.expression.StandardExpressionPreprocessor.preprocess(StandardExpressionPreprocessor.java:86)
	at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:120)
	at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:62)
	at org.thymeleaf.standard.expression.StandardExpressionParser.parseExpression(StandardExpressionParser.java:44)
	at org.thymeleaf.engine.EngineEventUtils.parseAttributeExpression(EngineEventUtils.java:220)
	at org.thymeleaf.engine.EngineEventUtils.computeAttributeExpression(EngineEventUtils.java:207)
	at org.thymeleaf.standard.processor.AbstractStandardExpressionAttributeTagProcessor.doProcess(AbstractStandardExpressionAttributeTagProcessor.java:125)
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314)
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
	at org.thymeleaf.engine.Model.process(Model.java:282)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1587)
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136)
	at org.thymeleaf.engine.TemplateManager.process(TemplateManager.java:519)
	at org.thymeleaf.standard.processor.AbstractStandardFragmentInsertionTagProcessor.doProcess(AbstractStandardFragmentInsertionTagProcessor.java:250)
	at org.thymeleaf.processor.element.AbstractAttributeTagProcessor.doProcess(AbstractAttributeTagProcessor.java:74)
	at org.thymeleaf.processor.element.AbstractElementTagProcessor.process(AbstractElementTagProcessor.java:95)
	at org.thymeleaf.util.ProcessorConfigurationUtils$ElementTagProcessorWrapper.process(ProcessorConfigurationUtils.java:633)
	at org.thymeleaf.engine.ProcessorTemplateHandler.handleOpenElement(ProcessorTemplateHandler.java:1314)
	at org.thymeleaf.engine.OpenElementTag.beHandled(OpenElementTag.java:205)
	at org.thymeleaf.engine.TemplateModel.process(TemplateModel.java:136)
	at org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:661)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1064)
```

I have worked around this for the time being by not embedding the underscores within the Thymeleaf expression:

```html
<span th:if="${d.e('Execution State')}" th:text="${d.gs('Execution State:LIKE THIS')}">EXECUTION STATE</span>
<span th:unless="${d.e('Execution State')}">____________________</span>
```

**Comment by duoduobingbing** [comment]
You need to escape double underscores because they start a pre-processing expression e.g. `${'myText__${"xyz"}__'}` resolves to `mytextxyz` because `__${'xyz'}__` will have the highest precedence.

`<span th:text="${d.gse('Execution State:LIKE THIS', '\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_')}" th:inline="none">____________________</span>` should do the trick

**Comment by danielfernandez** [comment]
@duoduobingbing 's answer is correct: due to the existence of the pre-processor, double-underscore sequences in expressions need to be escaped like `\_\_`, as mentioned in the [tutorial](https://www.thymeleaf.org/doc/tutorials/3.1/usingthymeleaf.html#preprocessing).
