### ISSUE TITLE
when using java 9 modules it doesn't find the template resolver

### ISSUE THREAD

**Issue by danilobatistaqueiroz** [thymeleaf/thymeleaf#994]
My project was working.  
I've started isolating my project inside Java 9 modules, then I've got this error:

`Error resolving template [carrinho/index.html], template might not exist or might not be accessible by any of the configured Template Resolvers`

Running: `./mvnw spring-boot:run` and accessing: `http://localhost:8080/carrinho` works fine, using or not Java 9 modules.

When testing using `mvn install` without `modules-info.java` it works.

My sample project with the problem:  
https://github.com/danilobatistaqueiroz/spring-boot-thymeleaf-java9-modules

Error full description:  
```sh
[ERROR] org.thymeleaf.exceptions.TemplateInputException: Error resolving template [carrinho/index.html], template might not exist or might not be accessible by any of the configured Template Resolvers
[ERROR]         at thymeleaf@3.1.2.RELEASE/org.thymeleaf.engine.TemplateManager.resolveTemplate(TemplateManager.java:869) ~[thymeleaf-3.1.2.RELEASE.jar:na]
[ERROR]         at thymeleaf@3.1.2.RELEASE/org.thymeleaf.engine.TemplateManager.parseAndProcess(TemplateManager.java:607) ~[thymeleaf-3.1.2.RELEASE.jar:na]
[ERROR]         at thymeleaf@3.1.2.RELEASE/org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1103) ~[thymeleaf-3.1.2.RELEASE.jar:na]
[ERROR]         at thymeleaf@3.1.2.RELEASE/org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1077) ~[thymeleaf-3.1.2.RELEASE.jar:na]
[ERROR]         at thymeleaf.spring6@3.1.2.RELEASE/org.thymeleaf.spring6.view.ThymeleafView.renderFragment(ThymeleafView.java:372) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:na]
[ERROR]         at thymeleaf.spring6@3.1.2.RELEASE/org.thymeleaf.spring6.view.ThymeleafView.render(ThymeleafView.java:192) ~[thymeleaf-spring6-3.1.2.RELEASE.jar:na]
[ERROR]         at spring.webmvc@6.1.3/org.springframework.web.servlet.DispatcherServlet.render(DispatcherServlet.java:1431) ~[spring-webmvc-6.1.3.jar:na]
[ERROR]         at spring.webmvc@6.1.3/org.springframework.web.servlet.DispatcherServlet.processDispatchResult(DispatcherServlet.java:1167) ~[spring-webmvc-6.1.3.jar:na]
[ERROR]         at spring.webmvc@6.1.3/org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1106) ~[spring-webmvc-6.1.3.jar:na]
[ERROR]         at spring.webmvc@6.1.3/org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.3.jar:na]
[ERROR]         at spring.webmvc@6.1.3/org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.3.jar:na]
[ERROR]         at spring.webmvc@6.1.3/org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:903) ~[spring-webmvc-6.1.3.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/jakarta.servlet.http.HttpServlet.service(HttpServlet.java:564) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at spring.webmvc@6.1.3/org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.3.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at spring.web@6.1.3/org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.3.jar:na]
[ERROR]         at spring.web@6.1.3/org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at spring.web@6.1.3/org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.1.3.jar:na]
[ERROR]         at spring.web@6.1.3/org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at spring.web@6.1.3/org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.3.jar:na]
[ERROR]         at spring.web@6.1.3/org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.3.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:340) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at org.apache.tomcat.embed.core@10.1.18/org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-10.1.18.jar:na]
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
[ERROR] 
[ERROR] .
[ERROR] '-- JUnit Jupiter [OK]
[ERROR]   +-- DemoApplicationTests [OK]
[ERROR]   | '-- contextLoads [OK]
```

**Comment by danielfernandez** [comment]
There are some issues related to the way modules are handled in that sample project. For instance, there should be lines in `module-info.java` opening the location of the templates to Thymeleaf, like e.g.:

```
  opens templates to thymeleaf, thymeleaf.spring6, spring.core;
  opens templates.carrinho to thymeleaf, thymeleaf.spring6, spring.core;
  opens templates.shared to thymeleaf, thymeleaf.spring6, spring.core;
  opens templates.shared.summary to thymeleaf, thymeleaf.spring6, spring.core;
  opens templates.vitrine to thymeleaf, thymeleaf.spring6, spring.core;
```
Other configurations are also missing, like: opening the applications packages to thymeleaf and thymeleaf.spring6 so that beans can be used, fixing `:` instead of `=` in `applicaiton.properties` avoiding templates to be referenceable by name (without `.html` suffix), etc.

Once fixed (and adapted to newer versions of the JDK), a `mvn clean compile test` seems to run OK.
